### ISSUE TITLE
No issues. Just want to say you are a life saver!

### ISSUE THREAD

**Issue by keganlester** [dpde/vapor-dockerfiles#1]
This helped me tons and pointed out my mistakes in the docker file. Will you be maintaining this repository?

**Comment by dpde** [comment]
Thanks a lot for your comment.

Yes, since I'm using this image myself for a project and want to also use it for another project, I'll maintain this repository and will also add a couple more images (e.g image that includes Libre Office).

If you have any suggestions on how to further improve it, please let me know.
